HW#7 - Done
yevhenii-khokhlov/Python-Enchantress pull request #11
Opened 2021-02-10 09:15 UTC by yevhenii-khokhlov

2021-02-10 09:16 UTC, yevhenii-khokhlov commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#7_sql_practice_Khokhlov_Yevhenii](https://trello.com/c/LpybbUS1/134-hw7sqlpracticekhokhlovyevhenii)

2021-02-14 17:38 UTC, dimigor requested changes

2021-02-14 17:38 UTC, dimigor commented on homework/sql_practice/main.py
> +                                           port='5432'
винеси присвоєння конфігів в ініт, а самі конфіги в константи

2021-02-14 17:38 UTC, dimigor commented on homework/sql_practice/tests_for_main.py
> +                         )
форматування так собі)

2021-02-22 09:12 UTC, dimigor approved these changes

2021-02-22 14:06 UTC, merged