add hw 3 tests
yevhenii-khokhlov/Python-Enchantress pull request #2
Opened 2021-01-14 20:17 UTC by yevhenii-khokhlov

2021-01-14 20:17 UTC, yevhenii-khokhlov commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#3-tests-Khokhlov-Yevhenii](https://trello.com/c/UYiLbgmN/56-hw3-tests-khokhlov-yevhenii)

2021-01-19 14:36 UTC, dimigor requested changes

2021-01-19 14:36 UTC, dimigor commented on homework/Unittest_simple_calc.py
> +        self.assertEqual(calc.divide(4, 4), 1.0)
Додай хибні випадки
Додай Випадки в яких може бути ексепшин, наприклад ділення на 0, або передача якихось інших типів даних в функцію

2021-01-19 14:36 UTC, dimigor commented on homework/Unittest_simple_calc.py
> +    """Class for making unittests of 'test_simple_calc.py' """
```suggestion
    """
    Class for making unittests of 'test_simple_calc.py' 
    """
```

2021-01-19 14:36 UTC, dimigor commented on homework/Unittest_simple_employee.py
> +from homework.tests_simple_employee import Employee
забагато пропусків між імортами

2021-01-19 16:37 UTC, yevhenii-khokhlov commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#3-tests-Khokhlov-Yevhenii](https://trello.com/c/UYiLbgmN/56-hw3-tests-khokhlov-yevhenii)

2021-01-22 19:03 UTC, dimigor approved these changes

2021-01-22 19:03 UTC, dimigor commented on homework/Unittest_simple_calc.py
> +        self.assertRaises(TypeError, lambda: calc.divide('one', 'two'))
краще розділяти тести

2021-01-23 15:32 UTC, merged