HW#11 is done
yevhenii-khokhlov/Python-Enchantress pull request #20
Opened 2021-02-28 19:22 UTC by yevhenii-khokhlov

2021-02-28 19:23 UTC, yevhenii-khokhlov commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#11_regex_Yevhenii_Khohklov](https://trello.com/c/btlCIzQ6/165-hw11regexyevheniikhohklov)

2021-03-14 16:40 UTC, dimigor requested changes

2021-03-14 16:40 UTC, dimigor commented on homework/regex/config_parser.py
> +        return text
винеси логіку по парсингу тексту і роботу з файлом в окреміі функції

2021-03-17 16:09 UTC, dimigor approved these changes

2021-03-17 16:09 UTC, dimigor commented on homework/regex/config_parser.py
> +def get_text(path) -> str:
доцільше було б назвати функцію get_text_from_file

2021-03-17 16:09 UTC, dimigor commented on homework/regex/some_website_parser.py
> +        raise Exception(f'Status_code is {r.status_code}')
```suggestion
    if r.status_code != 200:
        raise Exception(f'Status_code is {r.status_code}')
    return r.text
        
```

2021-03-17 16:16 UTC, merged