Hw 10 all done
yevhenii-khokhlov/Python-Enchantress pull request #23
Opened 2021-03-07 22:42 UTC by yevhenii-khokhlov

2021-03-07 22:43 UTC, yevhenii-khokhlov commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#10_flask_Khokhlov_Yevhenii](https://trello.com/c/MaLJJb8X/172-hw10flaskkhokhlovyevhenii)

2021-03-14 16:39 UTC, dimigor requested changes

2021-03-14 16:39 UTC, dimigor commented on homework/flask_login_hw/login_app/auth.py
> +    password = data['password']
використовуй метод ГЕТ дікта

2021-03-14 16:39 UTC, dimigor commented on homework/flask_login_hw/login_app/auth.py
> +    remember = True if data['remember'] else False
поганий вираз
в data['remember'] вже збергієаться булеве значення

2021-03-14 16:39 UTC, dimigor commented on homework/flask_login_hw/login_app/main.py
> +    db.session.commit()
Створи базовий клас для роботи з бд

2021-03-26 16:44 UTC, dimigor approved these changes

2021-03-26 16:54 UTC, dimigor approved these changes

2021-03-26 16:54 UTC, dimigor commented on homework/flask_login_hw/login_app/db_manager.py
> +        db.session.commit()
створи клас для роботи з базою даних

2021-03-26 16:54 UTC, dimigor commented on homework/flask_login_hw/.env
> +FLASK_ENV=development
незабувай про ендлайни

2021-03-26 17:46 UTC, yevhenii-khokhlov commented on homework/flask_login_hw/login_app/db_manager.py
> +        db.session.commit()
це якраз він і є. Чи я щосьне розумію

2021-03-26 17:47 UTC, yevhenii-khokhlov commented on homework/flask_login_hw/.env
> +FLASK_ENV=development
зараз виправлю

2021-03-30 09:57 UTC, merged