Hw pet hotel
yevhenii-khokhlov/Python-Enchantress pull request #27
Opened 2021-03-20 17:26 UTC by yevhenii-khokhlov

2021-03-20 17:26 UTC, yevhenii-khokhlov commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#12+13_flask+alembic_Khokhlov_Yevhenii](https://trello.com/c/gzJYfnvg/179-hw1213flaskalembickhokhlovyevhenii)

2021-04-02 19:34 UTC, dimigor requested changes

2021-04-02 19:34 UTC, dimigor commented on homework/pet_hotel_hw/pet_hotel/managers.py
> +        return (datetime.date.today() - check_in_date).days
цей клас більше нагадує бізнес логіку, але ніяк не роботу з БД
Клас який буде працювати з бд, може робити лише add, delete, commit

2021-04-08 11:51 UTC, Zaplatynskyi approved these changes

2021-04-08 19:35 UTC, merged